In [1]:
import pickle as pkl
import xgboost as xgb
from sklearn.model_selection import GridSearchCV
from sklearn.ensemble import RandomForestClassifier

with open('model.pkl','rb') as f:
    pickle = pkl.load(f)
    scalar = pickle[1]
    model = pickle[0]

XGBoostError: 
XGBoost Library (libxgboost.dylib) could not be loaded.
Likely causes:
  * OpenMP runtime is not installed
    - vcomp140.dll or libgomp-1.dll for Windows
    - libomp.dylib for Mac OSX
    - libgomp.so for Linux and other UNIX-like OSes
    Mac OSX users: Run `brew install libomp` to install OpenMP runtime.

  * You are running 32-bit Python on a 64-bit OS

Error message(s): ["dlopen(/Users/isang-yun/miniconda3/envs/capstonedesign/lib/python3.6/site-packages/xgboost/lib/libxgboost.dylib, 0x0006): Library not loaded: /usr/local/opt/libomp/lib/libomp.dylib\n  Referenced from: /Users/isang-yun/miniconda3/envs/capstonedesign/lib/python3.6/site-packages/xgboost/lib/libxgboost.dylib\n  Reason: tried: '/usr/local/opt/libomp/lib/libomp.dylib' (no such file), '/usr/local/lib/libomp.dylib' (no such file), '/usr/lib/libomp.dylib' (no such file)"]


In [2]:
model

XGBClassifier(base_score=0.5, booster='gbtree', callbacks=None,
              colsample_bylevel=1, colsample_bynode=1, colsample_bytree=0.75,
              early_stopping_rounds=None, enable_categorical=False,
              eval_metric=None, gamma=0, gpu_id=-1, grow_policy='depthwise',
              importance_type=None, interaction_constraints='',
              learning_rate=0.1, max_bin=256, max_cat_to_onehot=4,
              max_delta_step=0, max_depth=6, max_leaves=0, min_child_weight=1,
              missing=nan, monotone_constraints='()', n_estimators=1000,
              n_jobs=0, num_parallel_tree=1, predictor='auto', random_state=0,
              reg_alpha=0, reg_lambda=1, ...)

In [3]:
class off_angle: 
    def init():
        global off_records, angle_records
        off_records = [0]
        angle_records = []


    def detect(image, face_mesh_results):
        for face_no, face_landmarks in enumerate(face_mesh_results.multi_face_landmarks):
            for id, lm in enumerate(face_landmarks.landmark):
                shape = image.shape
                landmark_x = int(lm.x * shape[1])
                landmark_y = int(lm.y * shape[0])
                if id == 1 :
                    Nose=[landmark_x,landmark_y]
                if id == 127 :
                    Head_L=[lm.x,lm.y]
                if id == 356 :
                    Head_R=[lm.x,lm.y]
        off_distance = abs(Nose[0]-shape[1]/2)
        off_records.append(off_distance)
        come_off = max(off_records)-min(off_records)
        
        
        x_cord = abs(Head_L[0]-Head_R[0])
        z_cord = abs(Head_L[1]-Head_R[1])
        angle = round(math.atan2(x_cord/z_cord,2),2)*90-50
        if angle >90:
            angle = 90
        if angle < 0 :
            angle = 0
        angle_records.append(angle)
        face_angle = round(sum(angle_records)/len(angle_records))

        
        return come_off, face_angle

In [4]:
class moves_ZX:
    def init():
        global mX_start,rX_start, list_xX, list_yX, movement_recordX
        mX_start = pygame.time.get_ticks()
        rX_start = pygame.time.get_ticks()
        list_xX, list_yX, movement_recordX = [],[],[0]
        for k in range (33):
            list_xX.append(0)
            list_yX.append(0)


    def detect(results):
        global mX_start
        mX_passed = pygame.time.get_ticks() - mX_start
        if mX_passed > 50: 
            movement = 0
            delta = 0
            num_landmark = 0
            i=0
            for id, lm in enumerate(results.pose_landmarks.landmark):
                if lm.visibility > 0.7:
                    num_landmark +=1
                    delta_x = lm.x - list_xX[id]
                    delta_y = lm.y - list_yX[id]
                    delta = math.sqrt((delta_x * delta_x) + (delta_y * delta_y)) * 100
                    movement += delta
                else:
                    delta = 0
                del list_xX[id],list_yX[id]
                list_xX.insert(id,lm.x)
                list_yX.insert(id,lm.y)
            movement = movement/ num_landmark
            mX_passed = 0
            mX_start = pygame.time.get_ticks()
            movement_recordX.append(movement)
        if len(movement_recordX) == 2: # 영상별로 첫 번째 움직임 데이터는 불필요하여 삭제
            del movement_recordX[0]
            movement_recordX.append(0)
        movingX = round(sum(movement_recordX)/len(movement_recordX),3)
        return movingX
                            #movement = rou

In [5]:
class fer:
    def init():
        global angry_list, disgust_list, fear_list, happy_list, sad_list, surprise_list, neutral_list,emotion_list
        angry_list = [0]
        disgust_list = [0]
        fear_list = [0]
        happy_list = [0]
        sad_list = [0]
        surprise_list = [0]
        neutral_list = [0]
        emotion_list = [0,0,0,0,0,0,0]
        
    def detect(frame,emotions):
        try:
            for idx, data in enumerate(emotions[0]['emotions']):
                emotion=emotions[0]['emotions'][data]
                del emotion_list[idx]
                emotion_list.insert(idx,emotion)
            if emotion_list[6] != 0:
                angry_list.append(emotion_list[0])
                disgust_list.append(emotion_list[1])
                fear_list.append(emotion_list[2])
                happy_list.append(emotion_list[3])
                sad_list.append(emotion_list[4])
                surprise_list.append(emotion_list[5])
                neutral_list.append(emotion_list[6])
        except IndexError:
            pass
        if sum(neutral_list) == 0:
            fer_result = [0,0,0,0,0,0,0]
        else :
            fer_result = [sum(angry_list)/len(angry_list),sum(disgust_list)/len(disgust_list),sum(fear_list)/len(fear_list),sum(happy_list)/len(happy_list),sum(sad_list)/len(sad_list),sum(surprise_list)/len(surprise_list),sum(neutral_list)/len(neutral_list)]
        return fer_result

In [6]:
import cv2
import numpy as np
import mediapipe as mp
import itertools
import math
import glob,os
import csv
import pygame
from fer import FER
from fer.utils import draw_annotations
cap = cv2.VideoCapture(0)
mp_face_mesh = mp.solutions.face_mesh
mp_pose = mp.solutions.pose
mp_holistic = mp.solutions.holistic
detector = FER()

passed = 0
start = pygame.time.get_ticks()
pygame.init()
fer.init()
moves_ZX.init()
off_angle.init()
focus = 0
focus_prob = 0 
#try:   
with mp_face_mesh.FaceMesh(max_num_faces=1, refine_landmarks=True, min_detection_confidence=0.5, min_tracking_confidence=0.5) as face_mesh:
    with mp_pose.Pose(min_detection_confidence=0.5, min_tracking_confidence=0.5) as pose :
        while cap.isOpened():
            success, image = cap.read()
            if not success:
                print("Ignoring empty camera frame.")
                cap.release()
                cv2.destroyAllWindows()
            ######################################## 
            #각 모듈 불러오기
            image.flags.writeable = False
            image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)

            fm_results = face_mesh.process(image)
            pose_results = pose.process(image)

            image.flags.writeable = True
            image = cv2.cvtColor(image, cv2.COLOR_RGB2BGR)

            emotions = detector.detect_emotions(image)
            image = cv2.flip(image, 1)
            ########################################
            #데이터 추출
            try:
                fer_result = fer.detect(image,emotions)
                moving = moves_ZX.detect(pose_results)
                come_off , face_angle = off_angle.detect(image, fm_results)
            
            except Exception as e:

                    print("예외가 발생했습니다.", e)
            ########################################
            passed = pygame.time.get_ticks() - start # 시간측정
            if passed > 500 : # 2초, 1000 == 1초
                plus = [moving, face_angle,come_off] #탐지한 값들을 List로 합침
                row = fer_result + plus
                start = pygame.time.get_ticks()
                passed = 0
                fer.init() # 2초간의 데이터 초기화
                moves_ZX.init()
                off_angle.init()
                try:
                    X1 = scalar.transform(np.array(row).reshape(1,-1))
                    focus = model.predict(X1)[0]
                    focus_prob = model.predict_proba(X1)[0][1]

                except Exception as e:

                    print("예외가 발생했습니다.", e)








            # Make Detections

            cv2.putText(image, 'CLASS'
                                , (95,12), cv2.FONT_HERSHEY_SIMPLEX, 0.5, (0, 0, 0), 1, cv2.LINE_AA)

            cv2.putText(image, str(focus)
                        , (90,100), cv2.FONT_HERSHEY_SIMPLEX, 1, (0, 0, 0), 2, cv2.LINE_AA)

            # Display Probability
            cv2.putText(image, 'PROB'
                        , (15,12), cv2.FONT_HERSHEY_SIMPLEX, 0.5, (0, 0, 0), 1, cv2.LINE_AA)
            cv2.putText(image, str(round(focus_prob ,2))
                        , (10,40), cv2.FONT_HERSHEY_SIMPLEX, 1, (0, 0, 0), 2, cv2.LINE_AA)

            cv2.imshow('Blink', image)
            if cv2.waitKey(5) & 0xFF == 27:
                break
#except Exception as e:
    #print("예외가 발생했습니다.", e)  
#except Exception as e:
#print("예외가 발생했습니다.", e)                
cap.release()
cv2.destroyAllWindows()

pygame 2.1.2 (SDL 2.0.18, Python 3.7.13)
Hello from the pygame community. https://www.pygame.org/contribute.html


c:\Users\kangh\anaconda3\envs\capstone\lib\site-packages\tqdm\auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
c:\Users\kangh\anaconda3\envs\capstone\lib\site-packages\sklearn\base.py:451: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  "X does not have valid feature names, but"


[[-1.0965449  -0.14157473 -0.86849691 -0.27499795 -1.24704748 -0.37020263
  -2.15905455 16.51561048 -1.73478266  7.79546412]]
[[0.99120617 0.00879383]]
------------------
예외가 발생했습니다. 'NoneType' object is not iterable
[[-0.72121439 -0.14157473 -0.40881677  3.41430457  0.38093045 -0.21156813
  -2.10004116  6.82010306 -2.76063715  7.41044725]]
[[0.06174046 0.93825954]]
------------------


c:\Users\kangh\anaconda3\envs\capstone\lib\site-packages\sklearn\base.py:451: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  "X does not have valid feature names, but"
c:\Users\kangh\anaconda3\envs\capstone\lib\site-packages\sklearn\base.py:451: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  "X does not have valid feature names, but"


[[-1.0965449  -0.14157473 -0.86849691 -0.27499795 -1.24704748 -0.37020263
  -2.15905455  3.98466791 -0.31436876  4.92922741]]
[[0.9871455  0.01285454]]
------------------


c:\Users\kangh\anaconda3\envs\capstone\lib\site-packages\sklearn\base.py:451: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  "X does not have valid feature names, but"


[[-1.0965449  -0.14157473 -0.86849691 -0.27499795 -1.24704748 -0.37020263
  -2.15905455  3.02263842  0.63257385  0.48014356]]
[[0.9728406  0.02715941]]
------------------


c:\Users\kangh\anaconda3\envs\capstone\lib\site-packages\sklearn\base.py:451: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  "X does not have valid feature names, but"


[[-1.0965449  -0.14157473 -0.86849691 -0.27499795 -1.24704748 -0.37020263
  -2.15905455  3.10897932 -0.23545687  0.65126217]]
[[0.96903074 0.03096925]]
------------------


c:\Users\kangh\anaconda3\envs\capstone\lib\site-packages\sklearn\base.py:451: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  "X does not have valid feature names, but"


[[-1.0965449  -0.14157473 -0.86849691 -0.27499795 -1.24704748 -0.37020263
  -2.15905455  3.26477668 -0.86675194  1.42129591]]
[[0.996445   0.00355501]]
------------------


c:\Users\kangh\anaconda3\envs\capstone\lib\site-packages\sklearn\base.py:451: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  "X does not have valid feature names, but"


[[-1.0965449  -0.14157473 -0.86849691 -0.27499795 -1.24704748 -0.37020263
  -2.15905455  3.1899479  -1.18239948  1.80631279]]
[[0.9983112  0.00168879]]
------------------


c:\Users\kangh\anaconda3\envs\capstone\lib\site-packages\sklearn\base.py:451: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  "X does not have valid feature names, but"


[[-1.0965449  -0.14157473 -0.86849691 -0.27499795 -1.24704748 -0.37020263
  -2.15905455  3.33730303 -1.49804701  1.67797383]]
[[0.99788153 0.00211845]]
------------------


c:\Users\kangh\anaconda3\envs\capstone\lib\site-packages\sklearn\base.py:451: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  "X does not have valid feature names, but"


[[-1.0965449  -0.14157473 -0.86849691 -0.27499795 -1.24704748 -0.37020263
  -2.15905455  3.46662251 -1.5769589   4.15919367]]
[[0.99678624 0.00321376]]
------------------
예외가 발생했습니다. 'NoneType' object is not iterable


c:\Users\kangh\anaconda3\envs\capstone\lib\site-packages\sklearn\base.py:451: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  "X does not have valid feature names, but"


[[-1.0965449  -0.14157473 -0.86849691 -0.27499795 -1.24704748 -0.37020263
  -2.15905455  3.724494   -3.15519657  8.18048099]]
[[0.22078222 0.7792178 ]]
------------------


c:\Users\kangh\anaconda3\envs\capstone\lib\site-packages\sklearn\base.py:451: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  "X does not have valid feature names, but"


[[-1.0965449  -0.14157473 -0.86849691 -0.27499795 -1.24704748 -0.37020263
  -2.15905455  4.19725839  0.71148573  3.60305819]]
[[0.9968287  0.00317134]]
------------------


c:\Users\kangh\anaconda3\envs\capstone\lib\site-packages\sklearn\base.py:451: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  "X does not have valid feature names, but"


[[-1.0965449  -0.14157473 -0.86849691 -0.27499795 -1.24704748 -0.37020263
  -2.15905455  3.23638012  1.10604515  0.3518046 ]]
[[0.9846557  0.01534435]]
------------------


c:\Users\kangh\anaconda3\envs\capstone\lib\site-packages\sklearn\base.py:451: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  "X does not have valid feature names, but"


[[-1.0965449  -0.14157473 -0.86849691 -0.27499795 -1.24704748 -0.37020263
  -2.15905455  3.53723018  0.79039762  0.2662453 ]]
[[0.9017284 0.0982716]]
------------------


c:\Users\kangh\anaconda3\envs\capstone\lib\site-packages\sklearn\base.py:451: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  "X does not have valid feature names, but"


[[-0.88000806 -0.14157473 -0.69611686 -0.2511447  -0.80933643 -0.19173882
   0.69571821  5.25982707  1.10604515  0.52292321]]
[[0.2175762 0.7824238]]
------------------


c:\Users\kangh\anaconda3\envs\capstone\lib\site-packages\sklearn\base.py:451: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  "X does not have valid feature names, but"


[[-0.71544007 -0.14157473 -0.56970482 -0.27499795 -0.89687864  0.39124293
   0.75325627  3.79011309  1.18495703 -0.28989018]]
[[0.35009915 0.64990085]]
------------------


c:\Users\kangh\anaconda3\envs\capstone\lib\site-packages\sklearn\base.py:451: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  "X does not have valid feature names, but"


[[-0.88866954 -0.14157473  0.57949555 -0.27499795 -0.10439127  1.48582093
  -0.19390865  3.23331022  0.71148573 -0.16155122]]
[[0.8665965  0.13340347]]
------------------


c:\Users\kangh\anaconda3\envs\capstone\lib\site-packages\sklearn\base.py:451: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  "X does not have valid feature names, but"


[[-0.75008596 -0.14157473 -0.29389673 -0.27499795  0.84167892  0.18501809
  -0.72797983  3.61090775  0.71148573 -0.84602566]]
[[0.5499125 0.4500875]]
------------------


c:\Users\kangh\anaconda3\envs\capstone\lib\site-packages\sklearn\base.py:451: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  "X does not have valid feature names, but"


[[-1.0965449  -0.14157473 -0.86849691 -0.27499795 -1.24704748 -0.37020263
  -2.15905455  2.79277976  0.3958382  -0.67490705]]
[[0.05522841 0.9447716 ]]
------------------


c:\Users\kangh\anaconda3\envs\capstone\lib\site-packages\sklearn\base.py:451: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  "X does not have valid feature names, but"


[[-1.0965449  -0.14157473 -0.86849691 -0.27499795 -1.24704748 -0.37020263
  -2.15905455  2.73291674  0.15910255 -0.46100879]]
[[0.08816236 0.91183764]]
------------------


c:\Users\kangh\anaconda3\envs\capstone\lib\site-packages\sklearn\base.py:451: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  "X does not have valid feature names, but"


[[-1.0965449  -0.14157473 -0.86849691 -0.27499795 -1.24704748 -0.37020263
  -2.15905455  2.60129483  0.23801443 -0.16155122]]
[[0.42265236 0.57734764]]
------------------


c:\Users\kangh\anaconda3\envs\capstone\lib\site-packages\sklearn\base.py:451: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  "X does not have valid feature names, but"


[[-0.88000806 -0.14157473  0.56800354 -0.27499795 -0.74022416 -0.25122676
  -0.87551331  2.5690609   0.31692631 -0.6321274 ]]
[[0.4171347 0.5828653]]
------------------


c:\Users\kangh\anaconda3\envs\capstone\lib\site-packages\sklearn\base.py:451: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  "X does not have valid feature names, but"


[[-1.0965449  -0.14157473 -0.86849691 -0.27499795 -1.24704748 -0.37020263
  -2.15905455  2.75901087  0.3958382  -0.6321274 ]]
[[0.11270899 0.887291  ]]
------------------


c:\Users\kangh\anaconda3\envs\capstone\lib\site-packages\sklearn\base.py:451: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  "X does not have valid feature names, but"


[[-0.88000806 -0.14157473  0.1083234  -0.27499795 -0.18732599  0.10570085
  -1.05255348  2.55716504  0.94822138 -1.05992392]]
[[0.3646698 0.6353302]]
------------------


c:\Users\kangh\anaconda3\envs\capstone\lib\site-packages\sklearn\base.py:451: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  "X does not have valid feature names, but"


[[-0.80782912 -0.14157473  0.7403836  -0.27499795 -0.38698366  0.81955606
  -0.6247064   2.32193405  0.94822138 -1.10270358]]
[[0.5689964  0.43100357]]
------------------


c:\Users\kangh\anaconda3\envs\capstone\lib\site-packages\sklearn\base.py:451: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  "X does not have valid feature names, but"


[[-0.75008596 -0.14157473 -0.33220341 -0.27499795 -0.32555053  0.66092157
  -0.21161267  2.2175575   0.8693095  -1.31660184]]
[[0.12145102 0.878549  ]]
------------------


c:\Users\kangh\anaconda3\envs\capstone\lib\site-packages\sklearn\base.py:451: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  "X does not have valid feature names, but"


[[-0.8367007  -0.14157473 -0.66738685 -0.27499795 -0.64807446 -0.19173882
   0.62932815  3.3184999   0.94822138 -1.27382219]]
[[0.00980163 0.9901984 ]]
------------------


c:\Users\kangh\anaconda3\envs\capstone\lib\site-packages\sklearn\base.py:451: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  "X does not have valid feature names, but"


[[-0.79339333 -0.14157473  0.1083234  -0.27499795 -0.50984992  0.93853193
  -1.0746835   2.21947619  0.63257385 -0.97436462]]
[[0.369874 0.630126]]
------------------


c:\Users\kangh\anaconda3\envs\capstone\lib\site-packages\sklearn\base.py:451: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  "X does not have valid feature names, but"


[[-1.0965449  -0.14157473 -0.86849691 -0.27499795 -1.24704748 -0.37020263
  -2.15905455  2.24595406  0.3958382  -0.97436462]]
[[0.0792681 0.9207319]]
------------------


c:\Users\kangh\anaconda3\envs\capstone\lib\site-packages\sklearn\base.py:451: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  "X does not have valid feature names, but"


[[-1.0965449  -0.14157473 -0.86849691 -0.27499795 -1.24704748 -0.37020263
  -2.15905455  2.37181991  0.15910255 -0.88880531]]
[[0.01847869 0.9815213 ]]
------------------


c:\Users\kangh\anaconda3\envs\capstone\lib\site-packages\sklearn\base.py:451: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  "X does not have valid feature names, but"


[[-1.0965449  -0.14157473 -0.86849691 -0.27499795 -1.24704748 -0.37020263
  -2.15905455  2.37949465  0.15910255 -0.88880531]]
[[0.01847869 0.9815213 ]]
------------------


c:\Users\kangh\anaconda3\envs\capstone\lib\site-packages\sklearn\base.py:451: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  "X does not have valid feature names, but"


[[-1.0965449  -0.14157473 -0.86849691 -0.27499795 -1.24704748 -0.37020263
  -2.15905455  4.52765624  0.94822138  8.56549786]]
[[0.99284494 0.00715503]]
------------------
예외가 발생했습니다. 'NoneType' object is not iterable
[[ 0.92446554 -0.14157473  0.35731681 -0.27499795  0.53451328  0.10570085
  -1.68694743  7.95212819 -0.86675194  7.19654899]]
[[0.9926552  0.00734476]]
------------------


c:\Users\kangh\anaconda3\envs\capstone\lib\site-packages\sklearn\base.py:451: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  "X does not have valid feature names, but"
c:\Users\kangh\anaconda3\envs\capstone\lib\site-packages\sklearn\base.py:451: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  "X does not have valid feature names, but"


[[-1.0965449  -0.14157473 -0.86849691 -0.27499795 -1.24704748 -0.37020263
  -2.15905455  2.18839346 -2.36607773  5.48536289]]
[[0.93926954 0.06073044]]
------------------


c:\Users\kangh\anaconda3\envs\capstone\lib\site-packages\sklearn\base.py:451: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  "X does not have valid feature names, but"


[[-0.7067786  -0.14157473  0.62546356 -0.27499795  0.6880961  -0.25122676
  -1.67219408  3.23676385 -0.23545687  4.62976984]]
[[0.98424184 0.01575815]]
------------------


c:\Users\kangh\anaconda3\envs\capstone\lib\site-packages\sklearn\base.py:451: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  "X does not have valid feature names, but"


[[-0.89444385 -0.14157473  0.05086338 -0.24319362 -0.54056649  1.0575078
  -0.27062606  4.32926404  0.8693095   2.61912618]]
[[9.9971396e-01 2.8601597e-04]]
------------------


c:\Users\kangh\anaconda3\envs\capstone\lib\site-packages\sklearn\base.py:451: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  "X does not have valid feature names, but"


[[-1.0965449  -0.14157473 -0.86849691 -0.27499795 -1.24704748 -0.37020263
  -2.15905455  1.97848914  1.02713327 -0.71768671]]
[[0.18069756 0.81930244]]
------------------


c:\Users\kangh\anaconda3\envs\capstone\lib\site-packages\sklearn\base.py:451: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  "X does not have valid feature names, but"


[[-1.0965449  -0.14157473 -0.86849691 -0.27499795 -1.24704748 -0.37020263
  -2.15905455  1.97925662  1.18495703 -0.58934775]]
[[0.46857333 0.53142667]]
------------------


c:\Users\kangh\anaconda3\envs\capstone\lib\site-packages\sklearn\base.py:451: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  "X does not have valid feature names, but"


[[-0.66347123 -0.14157473  0.1083234  -0.2511447   0.43468444 -0.13225089
  -0.30013275  3.03875539  0.94822138 -0.5465681 ]]
[[0.08342379 0.9165762 ]]
------------------


c:\Users\kangh\anaconda3\envs\capstone\lib\site-packages\sklearn\base.py:451: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  "X does not have valid feature names, but"


[[-0.89444385 -0.14157473 -0.06405666  1.8558923  -0.8784487   3.83361141
  -1.583674    3.0337668   0.94822138 -0.50378844]]
[[0.976038   0.02396201]]
------------------


c:\Users\kangh\anaconda3\envs\capstone\lib\site-packages\sklearn\base.py:451: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  "X does not have valid feature names, but"


[[-1.0965449  -0.14157473 -0.86849691  5.76782514 -1.24704748  0.34365259
  -2.12954786  3.09938589  0.79039762 -0.46100879]]
[[0.6012801  0.39871994]]
------------------


c:\Users\kangh\anaconda3\envs\capstone\lib\site-packages\sklearn\base.py:451: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  "X does not have valid feature names, but"


[[-1.0965449  -0.14157473 -0.86849691 -0.27499795 -1.24704748 -0.37020263
  -2.15905455  3.03568549  0.55366196 -0.24711053]]
[[0.49835116 0.50164884]]
------------------


c:\Users\kangh\anaconda3\envs\capstone\lib\site-packages\sklearn\base.py:451: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  "X does not have valid feature names, but"


[[-1.0965449  -0.14157473 -0.86849691 -0.27499795 -1.24704748 -0.37020263
  -2.15905455  2.0099556   0.47475008 -0.20433088]]
[[0.5025825 0.4974175]]
------------------


c:\Users\kangh\anaconda3\envs\capstone\lib\site-packages\sklearn\base.py:451: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  "X does not have valid feature names, but"


[[-1.07489121 -0.14157473 -0.83976691  5.13968958 -1.1779352   0.10570085
  -1.51728393  3.1580977  -0.47219252  0.2662453 ]]
[[0.98551965 0.01448037]]
------------------


c:\Users\kangh\anaconda3\envs\capstone\lib\site-packages\sklearn\base.py:451: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  "X does not have valid feature names, but"


[[-0.98827648 -0.14157473 -0.66738685  4.49565186 -0.50984992  0.28416465
  -1.68325909  3.09209488 -0.78784006  0.52292321]]
[[0.88249564 0.11750434]]
------------------


c:\Users\kangh\anaconda3\envs\capstone\lib\site-packages\sklearn\base.py:451: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  "X does not have valid feature names, but"


[[-1.0965449  -0.14157473 -0.86849691  7.09088535 -1.24704748 -0.13225089
  -2.06168246  3.13660841  0.3958382   0.00956739]]
[[0.9441092  0.05589082]]
------------------


c:\Users\kangh\anaconda3\envs\capstone\lib\site-packages\sklearn\base.py:451: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  "X does not have valid feature names, but"


[[-1.06767332  0.12620071 -0.56204348  1.88769663 -0.72486588  5.0233701
  -1.583674    3.89640833  0.71148573  5.39980359]]
[[0.04246247 0.95753753]]
------------------


c:\Users\kangh\anaconda3\envs\capstone\lib\site-packages\sklearn\base.py:451: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  "X does not have valid feature names, but"


[[-1.0965449  -0.14157473 -0.86849691 -0.27499795 -1.24704748 -0.37020263
  -2.15905455  3.48235575 -2.60281339  8.00936238]]
[[0.92719996 0.07280004]]
------------------


c:\Users\kangh\anaconda3\envs\capstone\lib\site-packages\sklearn\base.py:451: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  "X does not have valid feature names, but"


[[-0.60572808 -0.14157473 -0.29389673  0.42469735 -0.8784487   2.24726649
  -0.66896644  5.55376986 -1.34022325  2.53356688]]
[[0.99581254 0.00418747]]
------------------


c:\Users\kangh\anaconda3\envs\capstone\lib\site-packages\sklearn\base.py:451: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  "X does not have valid feature names, but"


[[-1.0965449  -0.14157473 -0.86849691 -0.27499795 -1.24704748 -0.37020263
  -2.15905455  1.93666177 -3.23410845  2.23410931]]
[[0.7389846  0.26101542]]
------------------


c:\Users\kangh\anaconda3\envs\capstone\lib\site-packages\sklearn\base.py:451: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  "X does not have valid feature names, but"


[[-0.77895754 -0.14157473  0.7403836  -0.08417196 -0.8784487   3.19907344
  -0.91977335  3.20452992  0.79039762  1.03627904]]
[[0.92601436 0.07398562]]
------------------


c:\Users\kangh\anaconda3\envs\capstone\lib\site-packages\sklearn\base.py:451: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  "X does not have valid feature names, but"


[[-1.05323753 -0.14157473 -0.8110369   0.9176645  -1.20097263 -0.01327502
  -0.60995305  2.21717376  0.79039762  0.90794009]]
[[0.9774829  0.02251706]]
------------------


c:\Users\kangh\anaconda3\envs\capstone\lib\site-packages\sklearn\base.py:451: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  "X does not have valid feature names, but"


[[-0.98105859 -0.14157473 -0.79188356  1.31521865 -1.12418122  0.81955606
  -0.32963945  4.12242961 -0.15654499  3.8597361 ]]
[[0.56904656 0.43095344]]
------------------


c:\Users\kangh\anaconda3\envs\capstone\lib\site-packages\sklearn\base.py:451: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  "X does not have valid feature names, but"


[[-1.0965449  -0.14157473 -0.86849691 -0.27499795 -1.24704748 -0.37020263
  -2.15905455  2.47312656 -3.15519657  5.27146463]]
[[0.22078222 0.7792178 ]]
------------------


c:\Users\kangh\anaconda3\envs\capstone\lib\site-packages\sklearn\base.py:451: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  "X does not have valid feature names, but"


[[-1.0965449  -0.14157473 -0.86849691  4.40023886 -1.24704748 -0.37020263
  -2.13692453  3.09861841  0.63257385  3.13248201]]
[[9.999617e-01 3.835067e-05]]
------------------


c:\Users\kangh\anaconda3\envs\capstone\lib\site-packages\sklearn\base.py:451: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  "X does not have valid feature names, but"


[[-1.0965449  -0.14157473 -0.86849691  5.95865113 -1.24704748 -0.37020263
  -2.11479451  3.71758673  0.31692631 -0.71768671]]
[[0.04207081 0.9579292 ]]
------------------


c:\Users\kangh\anaconda3\envs\capstone\lib\site-packages\sklearn\base.py:451: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  "X does not have valid feature names, but"


[[-1.0965449  -0.14157473 -0.86849691  5.95865113 -1.24704748 -0.21156813
  -2.11479451  3.62548977 -0.07763311 -0.37544949]]
[[0.8879246  0.11207541]]
------------------


c:\Users\kangh\anaconda3\envs\capstone\lib\site-packages\sklearn\base.py:451: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  "X does not have valid feature names, but"


[[-1.0965449  -0.14157473 -0.86849691 -0.27499795 -1.24704748 -0.37020263
  -2.15905455  2.31272436 -0.07763311 -0.24711053]]
[[0.1909253 0.8090747]]
------------------


c:\Users\kangh\anaconda3\envs\capstone\lib\site-packages\sklearn\base.py:451: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  "X does not have valid feature names, but"


[[-1.0965449  -0.14157473 -0.86849691  3.3029894  -1.24704748  0.46262846
  -1.76071417  2.29392123 -0.15654499 -0.16155122]]
[[0.9492738  0.05072615]]
------------------


c:\Users\kangh\anaconda3\envs\capstone\lib\site-packages\sklearn\base.py:451: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  "X does not have valid feature names, but"


[[-0.88000806 -0.14157473 -0.69611686  1.82408796 -0.99363582  2.12829062
  -0.57675802  3.69648118 -0.94566383  3.00414305]]
[[0.99823195 0.00176805]]
------------------


c:\Users\kangh\anaconda3\envs\capstone\lib\site-packages\sklearn\base.py:451: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  "X does not have valid feature names, but"


[[-1.0965449  -0.14157473 -0.86849691 -0.27499795 -1.24704748 -0.37020263
  -2.15905455  2.83729329 -3.70757976  4.80088845]]
[[0.22078222 0.7792178 ]]
------------------


c:\Users\kangh\anaconda3\envs\capstone\lib\site-packages\sklearn\base.py:451: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  "X does not have valid feature names, but"


[[-1.0965449  -0.14157473 -0.75357688  0.24977353 -1.15489778  7.48220472
  -1.73858415  4.85191428 -1.34022325  3.56027853]]
[[0.9932596 0.0067404]]
------------------


c:\Users\kangh\anaconda3\envs\capstone\lib\site-packages\sklearn\base.py:451: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  "X does not have valid feature names, but"


[[-1.05323753 -0.14157473 -0.8110369   1.060784   -1.20097263  6.64937364
  -1.93775434  2.49077848 -2.60281339  4.11641402]]
[[0.3960836 0.6039164]]
------------------


c:\Users\kangh\anaconda3\envs\capstone\lib\site-packages\sklearn\base.py:451: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  "X does not have valid feature names, but"


[[-1.06767332 -0.14157473 -0.83019024  3.98678254 -1.18561435  0.18501809
  -1.36237378  2.07442347 -2.68172527  3.90251575]]
[[0.37831235 0.62168765]]
------------------


c:\Users\kangh\anaconda3\envs\capstone\lib\site-packages\sklearn\base.py:451: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  "X does not have valid feature names, but"


[[-1.07922195 -0.14157473 -0.75357688  1.86225316 -1.1180379   1.58100162
  -0.09653655  3.47391352  0.23801443  0.65126217]]
[[0.8860025  0.11399751]]
------------------


c:\Users\kangh\anaconda3\envs\capstone\lib\site-packages\sklearn\base.py:451: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  "X does not have valid feature names, but"


[[-0.98105859 -0.14157473 -0.33220341  2.71460926 -1.03203152  3.9922459
  -1.77546751  3.74252966  0.31692631 -0.03321227]]
[[0.7232396 0.2767604]]
------------------


c:\Users\kangh\anaconda3\envs\capstone\lib\site-packages\sklearn\base.py:451: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  "X does not have valid feature names, but"


[[-1.0965449  -0.14157473 -0.86849691 -0.27499795 -1.24704748 -0.37020263
  -2.15905455  2.54565292  0.31692631  0.09512669]]
[[0.51870567 0.48129433]]
------------------


c:\Users\kangh\anaconda3\envs\capstone\lib\site-packages\sklearn\base.py:451: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  "X does not have valid feature names, but"


[[-1.0965449  -0.14157473 -0.86849691 -0.27499795 -1.24704748 -0.37020263
  -2.15905455  2.48885979  0.15910255  0.05234704]]
[[0.37319797 0.626802  ]]
------------------


c:\Users\kangh\anaconda3\envs\capstone\lib\site-packages\sklearn\base.py:451: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  "X does not have valid feature names, but"


[[-0.79339333 -0.14157473  0.33816347  0.20206703 -0.74022416  0.22467672
  -1.14107357  2.5402806   0.15910255 -0.07599192]]
[[0.8040606  0.19593944]]
------------------


c:\Users\kangh\anaconda3\envs\capstone\lib\site-packages\sklearn\base.py:451: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  "X does not have valid feature names, but"


[[-0.4469344  -0.14157473  0.45308351 -0.06031871  1.03365745 -0.19173882
  -0.89764333  3.64045553  0.08019066 -0.20433088]]
[[0.23651755 0.76348245]]
------------------


c:\Users\kangh\anaconda3\envs\capstone\lib\site-packages\sklearn\base.py:451: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  "X does not have valid feature names, but"


[[-0.5768565  -0.14157473 -0.23643671  0.15436053 -0.4868125  -0.01327502
   0.00968755  3.54145129  0.08019066 -0.07599192]]
[[0.36403555 0.63596445]]
------------------


c:\Users\kangh\anaconda3\envs\capstone\lib\site-packages\sklearn\base.py:451: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  "X does not have valid feature names, but"


[[-6.63471231e-01 -1.41574726e-01 -2.93896732e-01 -1.79584954e-01
  -2.33400840e-01  2.63836029e-02 -2.41119361e-01  3.56370806e+00
   1.27877820e-03  9.56738532e-03]]
[[0.09120417 0.90879583]]
------------------


c:\Users\kangh\anaconda3\envs\capstone\lib\site-packages\sklearn\base.py:451: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  "X does not have valid feature names, but"


[[-1.00993016 -0.14157473 -0.69611686 -0.17958495 -0.786299   -0.25122676
  -0.34439279  3.61896624  0.08019066 -0.03321227]]
[[0.649259 0.350741]]
------------------


c:\Users\kangh\anaconda3\envs\capstone\lib\site-packages\sklearn\base.py:451: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  "X does not have valid feature names, but"


[[-0.3170123  -0.14157473 -0.29389673  0.82225151 -0.32555053 -0.13225089
  -0.47717292  3.5353115   0.15910255 -0.28989018]]
[[0.02573681 0.9742632 ]]
------------------


c:\Users\kangh\anaconda3\envs\capstone\lib\site-packages\sklearn\base.py:451: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  "X does not have valid feature names, but"


[[-0.75008596 -0.14157473 -0.56204348 -0.14778062 -0.3562671  -0.21156813
  -0.01981915  2.42324071 -0.07763311 -0.33266983]]
[[0.35420763 0.64579237]]
------------------


c:\Users\kangh\anaconda3\envs\capstone\lib\site-packages\sklearn\base.py:451: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  "X does not have valid feature names, but"


[[-1.07922195 -0.14157473 -0.73059287  2.77821793 -1.06274809  0.39124293
  -0.34439279  3.58251119  0.3958382  -0.28989018]]
[[0.9730825  0.02691752]]
------------------


c:\Users\kangh\anaconda3\envs\capstone\lib\site-packages\sklearn\base.py:451: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  "X does not have valid feature names, but"


[[-1.06767332 -0.14157473 -0.79188356  3.4461089  -1.21633091  1.92999751
  -1.42138717  3.74368087  0.71148573  3.81695645]]
[[0.61041754 0.38958246]]
------------------
예외가 발생했습니다. 'NoneType' object is not iterable
[[-1.0965449  -0.14157473 -0.86849691 -0.27499795 -1.24704748 -0.37020263
  -2.15905455  2.92094803  0.08019066  7.53878621]]
[[0.97384    0.02615998]]
------------------


c:\Users\kangh\anaconda3\envs\capstone\lib\site-packages\sklearn\base.py:451: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  "X does not have valid feature names, but"


예외가 발생했습니다. 'NoneType' object is not iterable
[[-1.0965449  -0.14157473 -0.86849691 -0.27499795 -1.24704748 -0.37020263
  -2.15905455  2.83383965 -2.91846092  7.49600655]]
[[0.37091702 0.629083  ]]
------------------


c:\Users\kangh\anaconda3\envs\capstone\lib\site-packages\sklearn\base.py:451: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  "X does not have valid feature names, but"


예외가 발생했습니다. 'NoneType' object is not iterable
예외가 발생했습니다. 'NoneType' object is not iterable
예외가 발생했습니다. 'NoneType' object is not iterable
예외가 발생했습니다. 'NoneType' object is not iterable
[[-1.0965449  -0.14157473 -0.86849691 -0.27499795 -1.24704748 -0.37020263
  -2.15905455  2.82923481 -2.9973728   6.51207455]]
[[0.37091702 0.629083  ]]
------------------


c:\Users\kangh\anaconda3\envs\capstone\lib\site-packages\sklearn\base.py:451: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  "X does not have valid feature names, but"


예외가 발생했습니다. 'NoneType' object is not iterable


c:\Users\kangh\anaconda3\envs\capstone\lib\site-packages\sklearn\base.py:451: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  "X does not have valid feature names, but"


[[-1.0965449  -0.14157473 -0.86849691 -0.27499795 -1.24704748 -0.37020263
  -2.15905455  3.07981528 -4.02322729  7.32488794]]
[[0.22078222 0.7792178 ]]
------------------
예외가 발생했습니다. 'NoneType' object is not iterable
예외가 발생했습니다. 'NoneType' object is not iterable
[[-1.0965449  -0.14157473 -0.86849691 -0.27499795 -1.24704748 -0.37020263
  -2.15905455  2.83230471 -3.15519657  7.58156586]]
[[0.22078222 0.7792178 ]]
------------------


c:\Users\kangh\anaconda3\envs\capstone\lib\site-packages\sklearn\base.py:451: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  "X does not have valid feature names, but"


예외가 발생했습니다. 'NoneType' object is not iterable
예외가 발생했습니다. 'NoneType' object is not iterable


c:\Users\kangh\anaconda3\envs\capstone\lib\site-packages\sklearn\base.py:451: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  "X does not have valid feature names, but"


[[-1.0965449  -0.14157473 -0.86849691 -0.27499795 -1.24704748 -0.37020263
  -2.15905455  3.16884235 -3.78649164  8.69383682]]
[[0.22078222 0.7792178 ]]
------------------


c:\Users\kangh\anaconda3\envs\capstone\lib\site-packages\sklearn\base.py:451: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  "X does not have valid feature names, but"


[[-1.0965449  -0.14157473 -0.86849691 -0.27499795 -1.24704748 -0.37020263
  -2.15905455  3.46086645 -3.94431541  9.12163335]]
[[0.22078222 0.7792178 ]]
------------------


c:\Users\kangh\anaconda3\envs\capstone\lib\site-packages\sklearn\base.py:451: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  "X does not have valid feature names, but"


[[-1.0965449  -0.14157473 -0.86849691 -0.27499795 -1.24704748 -0.37020263
  -2.15905455  3.90907166 -1.97151832  7.66712516]]
[[0.97509533 0.02490465]]
------------------


c:\Users\kangh\anaconda3\envs\capstone\lib\site-packages\sklearn\base.py:451: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  "X does not have valid feature names, but"


[[-1.07489121 -0.14157473 -0.86849691  5.28280907 -1.24704748 -0.25122676
  -1.46195888  4.55758775  0.63257385  1.2501773 ]]
[[9.9979013e-01 2.0988910e-04]]
------------------


c:\Users\kangh\anaconda3\envs\capstone\lib\site-packages\sklearn\base.py:451: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  "X does not have valid feature names, but"


[[-1.0965449  -0.14157473 -0.86849691  3.4842741  -1.24704748 -0.32261228
  -0.39750485  4.42020978  0.3958382   0.56570287]]
[[0.99831295 0.00168707]]
------------------


In [1]:
df.isnull()

NameError: name 'df' is not defined